Scope unscoped role types in define queries
graknlabs/graql pull request #190
Opened 2021-01-19 16:07 UTC by Phillammon

## What is the goal of this PR?

When a role type is overridden as part of a plays type definition, the overridden type is specified with no scope- we can infer the scope based on it being a supertype of the supplied role type, but at parse time this is not possible to infer without building the entire graph tree. In order to avert this, we supplied the root Relation type as a scope for the relation so it can be identified as a role type ahead of time, which leads to it being passed over for definition. Resolving this issue.

## What are the changes implemented in this PR?

We added the root RelationType as the scope for overridden RoleTypes in the Plays TypeConstraint.
We changed the way that the Plays TypeConstraint reports its RoleTypes to match this inferred type.

2021-01-19 18:15 UTC, flyingsilverfin commented on java/pattern/constraint/TypeConstraint.java
> +                }
i wonder if we can compress this into a one liner with the `?` syntax and itll fit? probably not, but worth a try to see if it looks nicer :)

2021-01-19 18:15 UTC, flyingsilverfin commented on java/pattern/constraint/TypeConstraint.java
> +            return returnString;
so if we don't have an established name for the string we build up and return, i think we can improve `returnString` to be something more meaningful, such as `syntax`

2021-01-19 18:15 UTC, flyingsilverfin requested changes
see comments inline

2021-01-19 18:17 UTC, flyingsilverfin commented
be careful with your titles - why is what you're doing specific to `define` queries? I believ its generic to any match or define  or undefine query actually, since you directly modified constraints. I think thats probably forgivable because you dont have a mental model yet of how Graql works. However, as you're writing your title and description is a good time to think and do one last check of your basic assumptions and understanding - maybe you could've questioned whether this was just for `Define`?.

As per the other PRs, add milestone, project, and labels plz

2021-01-20 10:26 UTC, flyingsilverfin approved these changes

2021-01-20 13:56 UTC, haikalpribadi approved these changes

2021-01-20 14:00 UTC, haikalpribadi commented
I've approved, but make sure to bump the dependency to graknlabs/behaviour repository first

2021-01-20 14:51 UTC, merged